### ISSUE TITLE
Are pre hooks and schema options inherited?

### ISSUE THREAD

**Issue by bitflower** [doasync/mongoose-extend-schema#2]
Hey, thanks for the new plugin!

I derive a schema from a "base schema" that has pre hooks on it and "timestamps".

Are they inherited?

See here: [https://github.com/Automattic/mongoose/issues/5897](https://github.com/Automattic/mongoose/issues/5897)

**Comment by doasync** [comment]
You're welcome!

Hooks are not inherited. You extend the copy of original object passed to the schema constructor. Use Schema plugins for hooks: [http://mongoosejs.com/docs/plugins.html](http://mongoosejs.com/docs/plugins.html)

**Comment by bitflower** [comment]
Ah, got it. Just had a look at the source and it's very basic ;-) Could've seen this myself....
